In [2]:
from sklearn.datasets import load_boston
#原来的验证器
#from sklearn.cross_validation import train_test_split

#新验证器
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.externals import joblib
import numpy as np

boston = load_boston()
# 查看数据描述
# print(boston.DESCR)   # 共506条波士顿地区房价信息，每条13项数值特征描述和目标房价
# 查看数据的差异情况
# print("最大房价：", np.max(boston.target))   # 50
# print("最小房价：",np.min(boston.target))    # 5
# print("平均房价：", np.mean(boston.target))   # 22.532806324110677

x = boston.data
y = boston.target
print(x)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [3]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=33)


# 3 训练数据和测试数据进行标准化处理
ss_x = StandardScaler()
x_train = ss_x.fit_transform(x_train)
x_test = ss_x.transform(x_test)

ss_y = StandardScaler()
y_train = ss_y.fit_transform(y_train.reshape(-1, 1))
y_test = ss_y.transform(y_test.reshape(-1, 1))

# 4.1 支持向量机模型进行学习和预测
# 线性核函数预测评估
# 线性核函数配置支持向量机并预测
linear_svr = SVR(kernel="linear")
linear_svr.fit(x_train, y_train)

c:\users\administrator.user-20190411rb\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NameError: name 'time' is not defined

In [4]:
import time

In [5]:
# 保存模型
mdhms = time.strftime('%d%H%M', time.localtime(time.time()))
file = 'joblib' + '_' + mdhms + '.mdp'
print("保存模型文件："+file)
joblib.dump(linear_svr,file)

保存模型文件：joblib_172157.mdp


['joblib_172157.mdp']

In [6]:
# 模型预测
linear_svr_y_predict = linear_svr.predict(x_test)

# 线性核函数 模型评估
print("线性核函数支持向量机的默认评估值为：", linear_svr.score(x_test, y_test))
print("线性核函数支持向量机的R_squared值为：", r2_score(y_test, linear_svr_y_predict))
print("线性核函数支持向量机的均方误差为:", mean_squared_error(ss_y.inverse_transform(y_test),
                                              ss_y.inverse_transform(linear_svr_y_predict)))
print("线性核函数支持向量机的平均绝对误差为:", mean_absolute_error(ss_y.inverse_transform(y_test),
                                                 ss_y.inverse_transform(linear_svr_y_predict)))

线性核函数支持向量机的默认评估值为： 0.650659546421538
线性核函数支持向量机的R_squared值为： 0.650659546421538
线性核函数支持向量机的均方误差为: 27.088311013556027
线性核函数支持向量机的平均绝对误差为: 3.4328013877599624
